export type ResReg  = {
    type: "reg",
    data:
        {
            name: string,
            index: number | string,
            error: boolean,
            errorText: string,
        } | string,
    id: 0,
}

export type ResUpdateWinners = {
    type: "update_winners",
    data: 
        [
            {
                name: string,
                wind: number
            }
        ] | string,
    id: 0,
}

export type ResUpdateRoom = {
    type: "update_room",
    data: {
        roomId: number | string;
        roomUsers: {}[];
    }[] | string,
    id: 0,
}

export type ResCreateGame = {
    type: "create_game", 
    data:
        {
            idGame: number | string,  
            idPlayer: number | string, /* generated by server id for player in the game session, not enemy (unique id for every player) */
        } | string,
    id: 0,
}

export type ResStartGame = {
    type: "start_game",
    data: 
    {
        ships: string,
        currentPlayerIndex: number | string | null,
    } | string,
    id: 0,
}

export type ResTurn = {
    type: "turn",
    data:
        {
            currentPlayer: number | string, /* id of the player in the current game session */
        } | string,
    id: 0,
}

export type ResAttack = {
    type: "attack",
    data:
        {
            position:
            {
                x: number,
                y: number,
            },
            currentPlayer: number | string, /* id of the player in the current game session */
            status: "miss"|"killed"|"shot",
        } | any,
    id: 0,
}

export type ResFinish = {
    type: "finish",
    data:
        {
            winPlayer: number | string, /* id of the player in the current game session */
        } | string,
    id: 0,
}